version: '3.8'

services:
  laravel_postgres:
    image: postgres
    #restart: always
    container_name: laravel_postgres
    env_file: ./docker/postgres/.env
    ports: 
      - 5432:5432
    expose: 
      - 5432
    
    volumes: 
      - './docker/postgres/my-postgres.conf:/etc/postgresql/postgresql.conf'
      - './docker/postgres/data:/var/lib/postgresql/data'
    command: 
      - '-c'
      - 'config_file=/etc/postgresql/postgresql.conf'
    networks: 
      - 'laravel_network'
  
  laravel_app:
    # image: laravel_app:0.1
    # container_name: laravel_app
    # build:
    #   context: ./docker/laravel
    #   dockerfile: ./Dockerfile.laravel
    build: './docker/laravel'
    image: laravel_app
    container_name: laravel_app
    expose: 
      - '9000'
    networks: 
      - 'laravel_network'
    volumes: 
      - './demo:/var/www/laravel'
    working_dir: '/var/www/laravel'
    depends_on: 
      - laravel_postgres
    
  
  server_nginx:
    image: nginx
    container_name: server_nginx
    depends_on: 
      - laravel_app
    volumes: 
      - './demo:/var/www/laravel'
      - ./docker/nginx/laravel.conf/:/etc/nginx/conf.d/laravel.conf
      - './docker/nginx/log:/var/log/nginx'
    ports: 
      - '80:80'
    networks: 
      - 'laravel_network'



networks:
  laravel_network:
    driver: bridge

volumes: 
  laravel_postgres_db:
